# Generated by Django 5.0 on 2025-12-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="relationship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("in_relationship", "In a Relationship"),
                    ("engaged", "Engaged"),
                    ("married", "Married"),
                    ("complicated", "It's Complicated"),
                    ("open_relationship", "In an Open Relationship"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
