# Generated by Django 5.0 on 2025-12-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_relationship_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dating_list_privacy",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("FRIENDS", "Friends Only"),
                    ("PRIVATE", "Private"),
                ],
                default="FRIENDS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="friends_list_privacy",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("FRIENDS", "Friends Only"),
                    ("PRIVATE", "Private"),
                ],
                default="PUBLIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_in_dating_search",
            field=models.BooleanField(default=True),
        ),
    ]
