# Generated by Django 5.0 on 2025-12-09 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message with the match request",
                        max_length=500,
                    ),
                ),
                ("match_score", models.FloatField(default=0.0)),
                ("response_at", models.DateTimeField(blank=True, null=True)),
                ("response_message", models.TextField(blank=True, max_length=500)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_match_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_match_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "match_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("messages_count", models.IntegerField(default=0)),
                ("last_interaction", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match",
                        to="dating.matchrequest",
                    ),
                ),
            ],
            options={
                "db_table": "matches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_age", models.IntegerField(default=18)),
                ("max_age", models.IntegerField(default=100)),
                (
                    "preferred_gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("ANY", "Any"),
                        ],
                        default="ANY",
                        max_length=20,
                    ),
                ),
                (
                    "max_distance",
                    models.IntegerField(
                        default=50, help_text="Maximum distance in kilometers"
                    ),
                ),
                ("preferred_location", models.CharField(blank=True, max_length=255)),
                (
                    "interests",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of interests"
                    ),
                ),
                (
                    "looking_for",
                    models.CharField(
                        choices=[
                            ("FRIENDSHIP", "Friendship"),
                            ("DATING", "Dating"),
                            ("RELATIONSHIP", "Relationship"),
                            ("ANY", "Any"),
                        ],
                        default="ANY",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user wants to appear in matches",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dating_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preferences",
            },
        ),
        migrations.AddIndex(
            model_name="matchrequest",
            index=models.Index(
                fields=["sender", "status"], name="match_reque_sender__ecf182_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchrequest",
            index=models.Index(
                fields=["receiver", "status"], name="match_reque_receive_f443e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="match_reque_status_875aa7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchrequest",
            unique_together={("sender", "receiver")},
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["user1", "is_active"], name="matches_user1_i_011e58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["user2", "is_active"], name="matches_user2_i_23570b_idx"
            ),
        ),
    ]
