# Generated by Django 5.0 on 2025-12-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("KNOWING", "Knowing Each Other"),
                    ("ACCEPTED", "Dating"),
                    ("REJECTED", "Rejected"),
                    ("BLOCKED", "Blocked"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
