# Generated by Django 5.0 on 2025-12-09 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCallSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("RINGING", "Ringing"),
                            ("ACTIVE", "Active"),
                            ("ENDED", "Ended"),
                            ("MISSED", "Missed"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="WAITING",
                        max_length=10,
                    ),
                ),
                (
                    "is_random",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a random Omegle-style call",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                (
                    "room_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "video_calls",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_random"],
                        name="video_calls_status_f87720_idx",
                    ),
                    models.Index(
                        fields=["caller", "status"],
                        name="video_calls_caller__5fd800_idx",
                    ),
                    models.Index(
                        fields=["receiver", "status"],
                        name="video_calls_receive_c66f5d_idx",
                    ),
                ],
            },
        ),
    ]
